learning_log/crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'
urlpatterns = [
    path('', views.home, name='home'),
    path('education/', views.education, name='education'),
    path('experience/', views.experience, name='experience'),
    path('message/', views.message, name='message'),
    path('contact/', views.contact, name='contact'),

]

learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls')),
]

learning_log/crud/models.py
from django.db import models

# Create your models here.

learning_log/crud/views.py
from django.shortcuts import render

# Create your views here.


educations = [
        {
            'date': 'JANUARY 2003 - JANUARY 2004',
            'stage': 'Primary institute',
            'desc': 'People only remember the First and forget the Rest',
            'name': 'Nou-Bahini institute,Dhaka',
        },
        {
            'date': 'FEBRUARY 2004- DECEMBER 2006 FEBRUARY 2011- MARCH 2014',
            'stage': 'Primary & Secondary institute',
            'desc': 'The Golden moment of my Life',
            'name': 'Nou-Bahini institute,Dhaka',
        }
    ]

experiences = [
    {
        'date': 'JOCTOBER 2021 - PRESENT',
        'stage': 'Software Development Engineer',
        'desc': 'Reactjs , Python, Django',
        'name': 'Datasoft Systems Bangladesh, LTD',
    },
    {
        'date': 'FEBRUARY 2021 - SEPTEMBER 2021',
        'stage': 'Full-stack Web Developer',
        'desc': 'Nodejs, Reactjs, AWS',
        'name': 'Doodle Technologies',
    }
]

details = {
    'email': 'mahidulmoon@gmail.com',
    'phone': '+8801771042196',
    'address': "YounusKhan's scholar's Garden Ashulia Savar, Dhaka."
}

links = {
    'f': 'https://www.facebook.com/mdmahidul.moon/',
    't': '',
    'i': 'https://www.instagram.com/m4h1dul_m00n/',
    'in': 'https://www.linkedin.com/authwall?trk='
          'bf&trkInfo=AQEtgCk16MjpuAAAAX85s524nsDG2UiMvBQAs8ePGeJCDF8aoEPEmHHnTYUdmKy_'
          'iFTQdDwJHoWWuTW3HLLK015oRbO_pA_fcgGs8vcO7N-bQzc1PhxdtXupy2VNZDAkKPIsv7U=&originalReferer='
          '&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fmahidul-moon-281509144%2F',
}

context = {
    'educations': educations,
    'experiences': experiences,
    'details': details,
    'links': links,
}


def home(request):
    return render(request, 'crud/index.html', context)


def education(request):
    return render(request, 'crud/education.html', context)


def experience(request):
    return render(request, 'crud/experience.html', context)


def message(request):
    return render(request, 'crud/message.html', context)


def contact(request):
    return render(request, 'crud/contact.html', context)

learning_log/crud/templates/crud/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'crud/images/react.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'crud/mystyle.css' %}">
    <title>Portfolio Mahidulmoon</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'crud:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crud:education' %}">Education</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crud:experience' %}">Experience</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crud:message' %}">Message</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crud:contact' %}">Contact</a>
      </li>
    </ul>
  </div>  
</nav>
<div class="greenstep"></div>
<h1 class="text-center mb-5 pointer">My <span style="font-family: robotoBold;">Resume</span></h1>

<div class="container">
  {% block content %}{% endblock %}
</div>
 <div class="footer bg-light p-4 text-muted">
        <div class="text-center">
            <a class="btn m-2 linkbtn" href="{{ links.f }}">f</a>
            <a class="btn m-2 linkbtn" href="#">t</a>
            <a class="btn m-2 linkbtn" href="{{ links.i }}">i</a>
            <a class="btn m-2 linkbtn" href="{{ links.in }}">in</a>
        </div>
        <p class=" text-center">This template made by <i class="fa fa-italic" aria-hidden="true">
            @Md. Madidul Islam</i> | copyright © 2022 All right reserved.</p>
 </div>
</body>
</html>

learning_log/crud/templates/crud/blocks.html
{% extends 'crud/base.html' %}
{% load static %}
{% block content %}

{% endblock %}

learning_log/crud/templates/crud/contact.html
{% extends 'crud/base.html' %}
{% load static %}
{% block content %}
<div class="gap"></div>
    <div class="greenstep"></div>
    <h2 class="text-center mb-5">Wanna <span style="font-family: robotoBold;">Start Work</span> With Me? </h2>
<h3 class="mb-5">My Contact Details</h3>
    {% if details %}
        <div class="mb-3">
            <b><small>EMAIL</small></b><br>
            <small>{{ details.email }}</small>
        </div>
        <div class="mb-3">
            <b><small>PHONE</small></b><br>
            <small>{{ details.phone }}</small>
        </div>
        <div class="mb-3">
            <b><small>ADDRESS</small></b><br>
            <small>
               {{ details.address }}
            </small>
        </div>
    {% endif %}
{% endblock %}

learning_log/crud/templates/crud/education.html
{% extends 'crud/base.html' %}
{% load static %}
{% block content %}
<h2 class="mt-4 mb-4 p-2">Education</h2>
            {% for edu in educations %}
                <div class="m-2 p-4 bg-light mysection">
                    <p class="small text-muted">{{ edu.date }}</p>
                    <h4>{{ edu.stage }}</h4>
                    <p class="small text-muted">{{ edu.desc }}</p>
                    <h6>{{ edu.name }}</h6>
                </div>
            {% endfor %}
{% endblock %}

learning_log/crud/templates/crud/experience.html
{% extends 'crud/base.html' %}
{% load static %}
{% block content %}
<h3 class="mt-4 mb-4 p-2">Experience</h3>
{% for exp in experiences %}
    <div class="m-2 p-4 bg-light mysection">
        <p class="small text-muted">{{ exp.date }}</p>
        <h4>{{ exp.stage }}</h4>
        <p class="small text-muted">{{ exp.desc }}</p>
        <h6>{{ exp.name }}</h6>
    </div>
{% endfor %}
{% endblock %}

learning_log/crud/templates/crud/index.html
{% extends 'crud/base.html' %}
{% load static %}
{% block content %}
<!-- Resume -->

    <div class="row">
        <!-- Education -->
        <div class="col-md-6">
            <h2 class="mt-4 mb-4 p-2">Education</h2>
            {% for edu in educations %}
                <div class="m-2 p-4 bg-light mysection">
                    <p class="small text-muted">{{ edu.date }}</p>
                    <h4>{{ edu.stage }}</h4>
                    <p class="small text-muted">{{ edu.desc }}</p>
                    <h6>{{ edu.name }}</h6>
                </div>
            {% endfor %}
        </div>

        <!-- Experience -->
        <div class="col-md-6">
            <h3 class="mt-4 mb-4 p-2">Experience</h3>

            {% for exp in experiences %}
                <div class="m-2 p-4 bg-light mysection">
                    <p class="small text-muted">{{ exp.date }}</p>
                    <h4>{{ exp.stage }}</h4>
                    <p class="small text-muted">{{ exp.desc }}</p>
                    <h6>{{ exp.name }}</h6>
                </div>
            {% endfor %}

        </div>
    </div>


    <!-- Form and contact details -->

    <div class="gap"></div>
    <div class="greenstep mt-5"></div>
    <h2 class="text-center mb-5">Wanna <span style="font-family: robotoBold;">Start Work</span> With Me? </h2>

    <div class="row">
        <!-- Form -->
        <div class="col-md-8 mb-5">
            <h3 class="mb-5">Information Please</h3>
            <form action="#">
                <div class="form-group mb-3">
                    <input type="text" class="form-control p-2" id="name" placeholder="Your Name" name="name">
                </div>

                <div class="form-group mb-3">
                    <input type="email" class="form-control p-2" id="email" placeholder="Your Email" name="email">
                </div>

                <div class="form-group mb-3">
                    <input type="text" class="form-control p-2" id="phone" placeholder="Your Phone" name="phone">
                </div>

                <div class="form-group">
                    <textarea class="form-control form" id="message" placeholder="Write a Message" name="message"
                        rows="10"></textarea>
                </div>

                <input type="submit" value="SEND MESSAGE" class="mybtn mt-5">
            </form>
        </div>

        <!-- Contact Details -->
        <div class="col-md-4">
            <h3 class="mb-5">My Contact Details</h3>

            {% if details %}
                <div class="mb-3">
                    <b><small>EMAIL</small></b><br>
                    <small>{{ details.email }}</small>
                </div>
                <div class="mb-3">
                    <b><small>PHONE</small></b><br>
                    <small>{{ details.phone }}</small>
                </div>
                <div class="mb-3">
                    <b><small>ADDRESS</small></b><br>
                    <small>
                       {{ details.address }}
                    </small>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

learning_log/crud/templates/crud/message.html
{% extends 'crud/base.html' %}
{% load static %}
{% block content %}
<div class="gap"></div>
    <div class="greenstep"></div>
    <h2 class="text-center mb-5">Wanna <span style="font-family: robotoBold;">Start Work</span> With Me? </h2>
 <h3 class="mb-5">Information Please</h3>
            <form action="#">
                <div class="form-group mb-3">
                    <input type="text" class="form-control p-2" id="name" placeholder="Your Name" name="name">
                </div>

                <div class="form-group mb-3">
                    <input type="email" class="form-control p-2" id="email" placeholder="Your Email" name="email">
                </div>

                <div class="form-group mb-3">
                    <input type="text" class="form-control p-2" id="phone" placeholder="Your Phone" name="phone">
                </div>

                <div class="form-group">
                    <textarea class="form-control form" id="message" placeholder="Write a Message" name="message"
                        rows="10"></textarea>
                </div>

                <input type="submit" value="SEND MESSAGE" class="mybtn mt-5">
            </form>
{% endblock %}